# -*- coding: utf-8 -*-
"""Health care-pations-analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VuhWP0dVUcgPtPpvGWz53kLnG69w3YbU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data={
"Patient_ID":np.random.randint(1,10000,10000),
"Age":np.random.randint(20,80,10000),
"Gender":np.random.choice(["Male","Female"],10000),
"Blood_Pressure":np.random.randint(80,180,10000),
"Sugar_Level":np.random.randint(70,200,10000),
"Cholesterol":np.random.randint(150,300,10000),
"Heart_Rate":np.random.randint(60,120,10000)
}

df=pd.DataFrame(data)

df.drop_duplicates(inplace=True)
df.fillna(df.mean(numeric_only=True),inplace=True)

def classify_risk(row):
    if(row["Blood_Pressure"]>140 or row["Sugar_Level"]>180 or row["Cholesterol"]>240 or row["Heart_Rate"]>100):return"High"
    elif(row["Blood_Pressure"]>120 or row["Sugar_Level"]>140 or row["Cholesterol"]>200):return"Medium"
    else:return"Low"

df["Risk_Level"]=df.apply(classify_risk,axis=1)

print(df.describe())
high_risk=df[df["Risk_Level"]=="High"]
print(len(high_risk))
print(df.groupby("Gender")["Blood_Pressure"].mean())
print(df.groupby("Risk_Level").size())

df["Age"].hist()
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()

df["Risk_Level"].value_counts().plot(kind="bar")
plt.title("Risk Level Distribution")
plt.show()

plt.scatter(df["Age"],df["Blood_Pressure"])
plt.xlabel("Age")
plt.ylabel("Blood Pressure")
plt.title("Age vs Blood Pressure")
plt.show()

sns.boxplot(x=df["Cholesterol"])
plt.title("Cholesterol Distribution")
plt.show()

corr=df.corr(numeric_only=True)
sns.heatmap(corr,annot=True)
plt.title("Correlation Heatmap")
plt.show()